name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # ou "master" se for seu caso
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/school-control-java:latest

      - name: Login no Docker Hub
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push da imagem (latest)
        run: docker push ghcr.io/${{ github.repository_owner }}/school-control-java:latest