name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # ou "master" se for seu caso
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/school-control:latest