name: Build Docker Image with bootBuildImage

on:
  push:
    branches:
      - main
    # opcional: só quando fizer tag
    # tags:
    #   - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Docker Image
        run: ./gradlew bootBuildImage

      # # Opcional: faça o push para Docker Hub ou GHCR
      # - name: Login no Docker Hub
      #   if: success()
      #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # - name: Push da imagem
      #   run: docker tag meu-app:latest ${{ secrets.DOCKER_USERNAME }}/meu-app:latest && docker push ${{ secrets.DOCKER_USERNAME }}/meu-app:latest
