name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write


    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permissions to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build Docker Image
        run: ./gradlew bootBuildImage --imageName=ghcr.io/${{ github.repository_owner }}/school-control-java:${{ github.sha }}

      - name: Login no Docker Hub
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push da imagem
        run: docker push ghcr.io/${{ github.repository_owner }}/school-control-java:${{ github.sha }}

      - name: Push da imagem (latest)
        run: docker push ghcr.io/${{ github.repository_owner }}/school-control-java:latest