name: Publish Javadoc to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch

permissions:
  contents: read # To checkout the repository
  pages: write    # To push to gh-pages branch
  id-token: write # To authenticate with GitHub Pages (if using OIDC)

jobs:
  publish-javadoc:
    name: Generate and Publish Javadoc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21' # Using LTS version for broader compatibility
          distribution: 'temurin' # Adoptium Temurin is a good choice
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Generate Javadoc
        run: ./gradlew javadoc

      - name: Deploy Javadoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/javadoc # Standard output directory for Javadoc
          # Optional: configure a custom domain, commit message, etc.
          # user_name: 'github-actions[bot]'
          # user_email: 'github-actions[bot]@users.noreply.github.com'
          # commit_message: 'Deploy Javadoc to GitHub Pages'
          # publish_branch: gh-pages # Default is gh-pages
          # allow_empty_commit: false
          # cname: docs.example.com
          # full_commit_message: ${{ github.event.head_commit.message }}
          # target_branch: another-branch # if you want to deploy to a different branch
          # keep_files: false # Remove all files from the branch before deploying
          # force_orphan: true # Create a new orphan branch every time
